### PR TITLE
Add file dev/.nosearch to keep dev/ off the load-path

### PR DESCRIPTION
**Pull request by tarsius**
As far as I can tell you are not actually using `dev/assess-discover.el`, but once you do you would have to load it using `load` instead of `require`. Since `assess` is a new testing utility, which hasn't quite taken off yet, I would like to take to you about not bundling libraries, and hopefully prevent something like https://github.com/rejeep/ert-runner.el/issues/38 ;-)

I think bundling libraries that are part of another package is generally a bad idea. There are cases where it might make sense, but they are less frequent than the practice is. One problem is that the bundles libraries could end up on the `load-path` and shadow the real version in cases where that was installed in its own right. This would be the case if someone used `normal-top-level-add-to-load-path`. Another issue is that this makes it hard to automatically extract features provided by a package. Just because a directory is named `dev` or `test`, that doesn't mean that it can simply be ignored when doing so, because there are yet other packages whose "real" libraries do depend on libraries placed in such directories.

Adding a `.nosearch` file prevents both of these issues, but I think it is better to just not bundle anything. And since this is a testing utility and testing utility are top candidates for being bundled, I hope that you can also do something to prevent package authors from doing so in this case.

### CODE REVIEW

**Comment by phillord** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> As far as I can tell you are not actually using
> `dev/assess-discover.el`, but once you do you would have to load it
> using `load` instead of `require`.

"make just-test"

> Since `assess` is a new testing utility, which hasn't quite taken off
> yet,

I'm overjoyed with the implication that assess will take off!

> I would like to take to you about not bundling libraries, and
> hopefully prevent something like
> https://github.com/rejeep/ert-runner.el/issues/38 ;-)
>
> I think bundling libraries that are part of another package is
> generally a bad idea. There are cases where it might make sense, but
> they are less frequent than the practice is.

In this case, the reason is quite specific: assess depends on m-buffer
(at all times!). Having m-buffer depend on assess also (even at dev
time) turns out to be a total PITA, especially when using melpa-stable,
because m-buffer depends on the last version of assess not the
latest. All of which fails if assess depends on a new feature of
m-buffer. I'm in this situation at the moment, as it happens.

Copying the only bit of assess I use was a pragmatic solution to the
problem and, incidentally, meant that I don't need ert-runner any more.


> Adding a `.nosearch` file prevents both of these issues, but I think
> it is better to just not bundle anything. And since this is a testing
> utility and testing utility are top candidates for being bundled, I
> hope that you can also do something to prevent package authors from
> doing so in this case.

It's a good point. There is no general reason to bundle assess; lentic
does not need to. But, other people may just copy what I have done in
m-buffer and think it is good, when, actually, it's a dependency kludge.

.nosearch is a good addition. Perhaps I should search and replace
"assess" with "kludged-assess" and rename the file likewise.

**Comment by tarsius** [comment]
> Perhaps I should search and replace "assess" with "kludged-assess" and rename the file likewise.

I think you should do that, and maybe add a notice explaining why that kludge is required in this case (but not for the readers own package).

Thanks for the explanation!

**Comment by tarsius** [comment]
Friendly ping!

**Comment by phillord** [comment]
Been putting this off, but actually, it was quite simple. Did the namespace munge also. Thanks for PR (and thanks for nagging!)

Closing in favour of https://github.com/phillord/m-buffer-el/commit/8681342aaffa187e5c54945ab91b812965a96d19

**Comment by tarsius** [comment]
Thanks!

**Pull request closed without merging**
